import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Navbar";
import { Montserrat } from "next/font/google";
import Footer from "@/components/Footer";
import { Analytics } from "@vercel/analytics/react";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Food Resource Hub | EWB UofT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased flex flex-col min-h-screen`}>
        <Nav />
        <main className="pt-20 md:pt-32 lg:pt-40 flex-1">
          {children}
        </main>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}