import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Navbar";
import { Source_Sans_3 } from 'next/font/google'

const sourceSans3 = Source_Sans_3({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-source-sans-3',
})

export const metadata: Metadata = {
  title: "Food Resource Hub | EWB UofT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sourceSans3.variable}antialiased overflow-x-auto min-w-max`}>
        <div>
          <main>
            <Nav/>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
